remote_theme: konstantin-morenko/just-the-docs-reborn

title: Книжные вырезки
description: Коллекция книжных вырезок от Константина Моренко

aux_links:
  "Константин Моренко":
    - "https://konstantin-morenko.ru"
  "Все проекты":
    - "https://konstantin-morenko.ru/all-projects"

ycnumber: 69954367